### PR TITLE
Added/Fixed cardEquipMap.

### PR DESCRIPTION
**Pull request by Morta1**

### CODE REVIEW

**Comment by Corbeno** [comment]
Did you check that these changes work for the idleon calculator spreadsheet? That is why they are hardcoded like this

**Comment by Morta1** [comment]
I changed the description only, does it affect the spreadsheet?

**Comment by Corbeno** [comment]
Yes it does. It's strange I know but that's just how the spreadsheet works. It's the only thing this mapping is used for, so I would suggest using mobMap instead

**Comment by Morta1** [comment]
I wanted to update it to be able to get the right description for the equipped cards for every character.
How would you suggest doing this?

**Comment by Corbeno** [comment]
I'm not sure getting a card's description is in the scope of this extension. It's not really related to save data. 

If you wanted to create a new map that maps card's names to some sort of description I wouldn't be against it, but again I'm not sure it's the focus of this project.

**Pull request closed without merging**
